### ISSUE TITLE
Integration Roadmap

### ISSUE THREAD

**Issue by DaQuirm** [21-23/_qd#1]
- [x] redemption can connect to arnaux
- [x] zandbak-service can connect to arnaux
- [x] front-service can start
- [x] front-service can connect to arnaux
- [x] front-service can serve an app
- [x] user can send a test message to redemption
- [x] end2end message circuit (solution flow)

**Comment by DaQuirm** [comment]
Finally, this is done, omg 😹
